Repository eduNEXT/eox-audit-model, pull requests merged in 2024-10, with the labels that each got.

#34 chore(ci): remove integration tests workflow
  .github/workflows/integration-test.yml
  eox_audit_model/tests/tutor/__init__.py
  eox_audit_model/tests/tutor/conftest.py
  eox_audit_model/tests/tutor/integration.sh
  eox_audit_model/tests/tutor/integration_test_tutor.py
  eox_audit_model/tests/tutor/pytest.ini
Labels: size/s

#36 ci: add dependabot config for enable github action auto update `AP-1514`
  .github/dependabot.yml
  .github/workflows/bump_version.yml
  .github/workflows/labeler.yml
  .github/workflows/python-publish.yml
Labels: size/xs

#35 chore: drop support for Python 3.10 and Django 3.2
  .github/workflows/tests.yml
  CHANGELOG.md
  README.rst
  eox_audit_model/__init__.py
  requirements/base.txt
  requirements/pip-tools.txt
  requirements/test.txt
  requirements/tox.txt
  setup.cfg
  setup.py
  tox.ini
Labels: size/m
